using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using DGCodeGen.Engine;
using DGCodeGen.TypeConversions;
using TestLib.Grasshopper;

namespace TestLib.DGCommon
{
    /// <summary>
    /// Classes of type TypeConversion will be loaded into the TypeDictionary.
    /// This class should be autogenerated!!
    /// </summary>
    //public class SomeDataConversion : CustomClassConversion<SomeData, SomeData_Goo>
    //{
    //    public override string Gh_CustomParameterName => nameof(SomeData_Param);
    //}
}